In [ ]:
!pip install tensorflow
import numpy as np
import tensorflow as tf

In [6]:
np.set_printoptions(precision=5)
a = np.array([1, 2, 3, 4, 5],dtype=np.int32)
b = [6, 7, 8, 9, 10]
t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)
t_one = tf.ones((2,5))
t_one.shape

TensorShape([2, 5])

In [8]:
tf.fill((5,3),1)

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])>

In [10]:
tf.one_hot([1,3,5],6)

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [14]:
tf.random.set_seed(42)
t1 = tf.random.uniform(shape=(5,3), minval=1.0, maxval=10)
t2 = tf.random.normal(shape=(5,3), mean=0.0, stddev=1.0)
print(t1)
print(t2)

tf.Tensor(
[[6.98106 4.96906 4.17594]
 [5.18034 1.30294 7.16205]
 [7.66106 8.852   3.03694]
 [3.00877 3.79349 7.50102]
 [2.19868 5.93257 6.17148]], shape=(5, 3), dtype=float32)
tf.Tensor(
[[ 8.42246e-02 -8.60904e-01  3.78123e-01]
 [-5.19627e-03 -4.94532e-01  6.17819e-01]
 [-3.30820e-01 -1.38408e-03 -4.23734e-01]
 [-1.38721e+00 -1.54882e+00 -5.31984e-01]
 [-4.47564e-01 -2.01158e+00 -5.79260e-01]], shape=(5, 3), dtype=float32)


In [16]:
t = tf.multiply(t1,t2).numpy()
print(t)

[[  0.58798  -4.27788   1.57902]
 [ -0.02692  -0.64435   4.42485]
 [ -2.53443  -0.01225  -1.28685]
 [ -4.17379  -5.87543  -3.99042]
 [ -0.98405 -11.93386  -3.57489]]


In [20]:
a=[1.1,3.6, 4.5, 2.1, 5.0, 6.2, 2.2, 3.4]
ds = tf.data.Dataset.from_tensor_slices(a)
print(ds)
for i in ds:
    print(i)
# create a batch
ds_batch = ds.batch(2)
for i, e in enumerate(ds_batch,1):
    print('batch{}:'.format(i), e.numpy())

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.float32, name=None)>
tf.Tensor(1.1, shape=(), dtype=float32)
tf.Tensor(3.6, shape=(), dtype=float32)
tf.Tensor(4.5, shape=(), dtype=float32)
tf.Tensor(2.1, shape=(), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor(6.2, shape=(), dtype=float32)
tf.Tensor(2.2, shape=(), dtype=float32)
tf.Tensor(3.4, shape=(), dtype=float32)
batch1: [1.1 3.6]
batch2: [4.5 2.1]
batch3: [5.  6.2]
batch4: [2.2 3.4]


In [22]:
tf.random.set_seed(42)
tx = tf.random.uniform([5,3], dtype=tf.float32)
ty = tf.range(5)
dsX = tf.data.Dataset.from_tensor_slices(tx)
dsY = tf.data.Dataset.from_tensor_slices(ty)
ds_merge = tf.data.Dataset.zip((dsX,dsY))
for i in ds_merge:
    print(' x: ', i[0].numpy(), ' y: ', i[1].numpy())

 x:  [0.66456 0.44101 0.35288]  y:  0
 x:  [0.46448 0.03366 0.68467]  y:  1
 x:  [0.74012 0.87244 0.22633]  y:  2
 x:  [0.2232  0.31039 0.72234]  y:  3
 x:  [0.13319 0.54806 0.57461]  y:  4


In [24]:
tf.random.set_seed(1)
ds = ds_merge.shuffle(buffer_size=len(tx))
for i in ds:
    print(' x: ', i[0].numpy(), ' y: ', i[1].numpy())

 x:  [0.46448 0.03366 0.68467]  y:  1
 x:  [0.74012 0.87244 0.22633]  y:  2
 x:  [0.66456 0.44101 0.35288]  y:  0
 x:  [0.13319 0.54806 0.57461]  y:  4
 x:  [0.2232  0.31039 0.72234]  y:  3


In [26]:
ds = ds_merge.batch(batch_size=2, drop_remainder=False)
batch_x, batch_y = next(iter(ds))
print('batch x: \n', batch_x.numpy())
print('batch y: \n', batch_y.numpy())
print('Bactch:\n')
for i in ds:
    print(i[0].numpy(),' ',i[1].numpy())

batch x: 
 [[0.66456 0.44101 0.35288]
 [0.46448 0.03366 0.68467]]
batch y: 
 [0 1]
Bactch:

[[0.66456 0.44101 0.35288]
 [0.46448 0.03366 0.68467]]   [0 1]
[[0.74012 0.87244 0.22633]
 [0.2232  0.31039 0.72234]]   [2 3]
[[0.13319 0.54806 0.57461]]   [4]


In [40]:
ds = ds_merge.batch(3).repeat(count=3)
for i, (batchx, batchy) in enumerate(ds):
    print(i, batch_x.shape, batch_y.numpy())

0 (2, 3) [4 1]
1 (2, 3) [4 1]
2 (2, 3) [4 1]
3 (2, 3) [4 1]
4 (2, 3) [4 1]
5 (2, 3) [4 1]


In [38]:
ds = ds_merge.shuffle(4).batch(3).repeat(10)
for i, (batch_x, batch_y) in enumerate(ds):
    print(i, batch_x.shape, batch_y.numpy())

0 (3, 3) [2 0 1]
1 (2, 3) [4 3]
2 (3, 3) [0 2 1]
3 (2, 3) [3 4]
4 (3, 3) [1 0 3]
5 (2, 3) [4 2]
6 (3, 3) [1 3 0]
7 (2, 3) [4 2]
8 (3, 3) [0 4 2]
9 (2, 3) [1 3]
10 (3, 3) [2 3 0]
11 (2, 3) [4 1]
12 (3, 3) [1 3 0]
13 (2, 3) [4 2]
14 (3, 3) [3 2 0]
15 (2, 3) [1 4]
16 (3, 3) [3 4 1]
17 (2, 3) [0 2]
18 (3, 3) [3 0 2]
19 (2, 3) [4 1]
